pipeline:
  name: test
  identifier: test
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github
        repoName: s3-cleaner
        build: <+input>
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "hello"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
