name: CI

on:
  push:
    branches:
      - first-tag

jobs:
  update-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config user.name "Pratikkumar Mohite"
        git config user.email "mohite770.pm@gmail.com"
    
    - name: Get the latest tag
      id: get_latest_tag
      run: |
        git describe --tags --abbrev=0

    - name: Increment version
      id: increment_version
      run: |
        latest_tag=${{ steps.get_latest_tag.outputs.latest_tag }}
        IFS='.' read -r -a version_parts <<< "$latest_tag"
        major=${version_parts[0]}
        minor=${version_parts[1]}
        patch=${version_parts[2]}
        new_patch=$((patch + 1))
        new_tag="$major.$minor.$new_patch"
        echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

    - name: Create and push new tag
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TAG_PUSH_TOKEN }}
      run: |
        new_tag=${{ steps.increment_version.outputs.new_tag }}
        git tag -a $new_tag -m "Release $new_tag"
        git push origin $new_tag